### ISSUE TITLE
types_test.go question. 

### ISSUE THREAD

**Issue by DanielKrawisz** [monetas/bmutil#1]
In types_test.go TestVarStringOverflowError, you removed the expected error field. Is there some reason for that you don't want to test for that anymore?

**Comment by ishbir** [comment]
Oh yeah, that's because I made varstring independent of wire. It used to give a wire.MessageError which doesn't make sense if interpreted independently from a message. I personally think that in this case, a generic error is good enough. Let me know if you think that returning a specific error would be better and I'll change it.
